### ISSUE TITLE
[BUG] Events displayed on the log do not appear in the GraphQL endpoint

### ISSUE THREAD

**Issue by RafaDSan** [ponder-sh/ponder#886] opened 2024-05-15 01:34 UTC
### Version 
`"@ponder/core": "^0.4.24"`

### Bug Found
When running `npm run dev` it logs the total events emitted on the console, however, when trying to fetch the same events through the GraphQL endpoint, it fetches nothing. Also, the total number in the log is wrong, fetching only 3 instead of the total events in [this](https://sepolia.kakarotscan.org/address/0xB317127b50b22e62637E3c333A585a8ccfd0721D/events) link
Obs: The problem only happens in the `kakarot` network

#### 1. Result of running `npm run dev`
![image](https://github.com/ponder-sh/ponder/assets/102108966/2a0b5e1c-b7d5-4191-af22-ca84237e6f09)

#### 2. Result of running a query to fetch the events related to the `kakarot` network logged in the console

![image](https://github.com/ponder-sh/ponder/assets/102108966/28e0a02f-b6be-428c-8880-cac443036604)

### Steps to reproduce

1. clone [this](https://github.com/RafaDSan/swaplace-subgraph/tree/ponder) repository
2. Run `npm run dev`
3. Check the log
4. Run the following graphql in the endpoint:
```graphql
query MyQuery {
  swapDatabases(
    orderBy: "blockTimestamp"
    orderDirection: "desc"
    where: {network: "1802203764"}
  ) {
    items {
      swapId
      status
      allowed
      ask
      bid
      blockTimestamp
      expiry
      id
      transactionHash
      owner
      recipient
      value
      network
    }
  }
}
```
5. Compare the result with the previous log.

### Update
For some reason, the number of events keeps increasing in the ponder log, but in fact none new were created in the blockchain
![image](https://github.com/ponder-sh/ponder/assets/102108966/5761c878-8437-4f6a-bbeb-e4fe67603c93)

**Comment by 0xOlias** [comment] 2024-05-17 04:26
@kyscott18 started working on a reproduction here, and found another Kakarot RPC bug. 

It looks like [EIP-234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md) `eth_getLogs` requests return all logs on the chain, regardless of which block they were emitted in. Can reproduce with this request:

```
curl -X POST -H "Content-Type: application/json" --data '{
    "jsonrpc": "2.0",
    "method": "eth_getLogs",
    "params": [{
        "blockHash": "0x020dc933dc5772707a9b78f76010b2c538d3e55423646481ccefa56ae0a7e887"
    }],
    "id": 1
}' https://sepolia-rpc.kakarot.org
```

We work hard to triage, reproduce, and fix every bug report that we receive. It’s time-consuming work. Unfortunately, after two incidents of non-compliance, we can’t accept bug reports for apps using Kakarot until we see evidence that they are thoroughly testing their RPC ([related issue](https://github.com/kkrt-labs/kakarot-rpc/issues/1055)).

Closing for now. There may indeed be a Ponder bug here, and we will gladly revisit once the Kakarot RPC test coverage has improved.

**Closed by 0xOlias** 2024-05-17 04:26 UTC

**Comment by RafaDSan** [comment] 2024-05-17 14:37
Hey @0xOlias thank you for making it clear and for your efforts! I'll talk to them

**Comment by 0xneves** [comment] 2024-05-28 13:43
> @kyscott18 started working on a reproduction here, and found another Kakarot RPC bug.
> 
> It looks like [EIP-234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md) `eth_getLogs` requests return all logs on the chain, regardless of which block they were emitted in. Can reproduce with this request:
> 
> ```
> curl -X POST -H "Content-Type: application/json" --data '{
>     "jsonrpc": "2.0",
>     "method": "eth_getLogs",
>     "params": [{
>         "blockHash": "0x020dc933dc5772707a9b78f76010b2c538d3e55423646481ccefa56ae0a7e887"
>     }],
>     "id": 1
> }' https://sepolia-rpc.kakarot.org
> ```
> 
> We work hard to triage, reproduce, and fix every bug report that we receive. It’s time-consuming work. Unfortunately, after two incidents of non-compliance, we can’t accept bug reports for apps using Kakarot until we see evidence that they are thoroughly testing their RPC ([related issue](https://github.com/kkrt-labs/kakarot-rpc/issues/1055)).
> 
> Closing for now. There may indeed be a Ponder bug here, and we will gladly revisit it once the Kakarot RPC test coverage has improved.

Hey @0xOlias , Could you provide a link explaining how to check compliance for Ponder? I've looked up Ponder's repos and docs but nowhere to find them. I would like to have access to this "triage" process to help other chains to implement Ponder. Thank you in advance
