### ISSUE TITLE
[BUG] Database error while running insertLogFilterInterval

### ISSUE THREAD

**Issue by 0xneves** [ponder-sh/ponder#818] opened 2024-04-19 23:55 UTC
### Version

`"@ponder/core": "^0.4.7"`

### Bug found

```
...
WARN  historical Block task failed, retrying... [4617] (network=kakarot, error=TypeError: Cannot read properties of undefined (reading 'toString'))
WARN  sync Database error while running insertLogFilterInterval, retrying after 100 milliseconds. Error: Cannot read properties of undefined (reading 'toString')
...
```

![pondererrror](https://github.com/ponder-sh/ponder/assets/90667119/d46176ab-17c4-4854-9a53-ffe9b45bd536)

### Steps to reproduce

1. [Clone this repo](https://github.com/blockful-io/swaplace-subgraph/tree/ponder) in the `ponder` branch
2. Add the public RPC of Kakarot: `https://sepolia-rpc.kakarot.org`
3. Run `npm run ponder` or others alike

### Additional Context

There is only one RPC available in the entire world at the moment as the chain is on alpha

**Comment by ChiTimesChi** [comment] 2024-04-20 10:17
This might be helpful, it seems as if the `size` field in the kakarot blocks is null:

```bash
$ cast bl -r https://sepolia-rpc.kakarot.org --json | jq .
{
  "hash": "0x052f14a4fa6271b93dd48996e38d45633a5958d1b2d79d68405114b758828836",
  "parentHash": "0x05003cf2c38f8bafd8b82a4617ff47dc2c2dd8fc5f8792e98139fc753f3d782e",
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "miner": "0xca40796afb5472abaed28907d5ed6fc74c04954a",
  "stateRoot": "0x06eff4a5dc5808ca81ad5702fb4ec1510424cdfc8690167a4e7617511af9e962",
  "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  "number": "0x1228",
  "gasUsed": "0x0",
  "gasLimit": "0x1312d00",
  "extraData": "0x",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x662384f2",
  "difficulty": "0x0",
  "totalDifficulty": "0x0",
  "sealFields": [],
  "uncles": [],
  "transactions": [],
  "size": null,
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "nonce": "0x0000000000000000",
  "baseFeePerGas": "0x0",
  "withdrawalsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  "withdrawals": []
}
```

**Comment by RafaDSan** [comment] 2024-04-26 13:27
> This might be helpful, it seems as if the `size` field in the kakarot blocks is null:
> 
> ```shell
> $ cast bl -r https://sepolia-rpc.kakarot.org --json | jq .
> {
>   "hash": "0x052f14a4fa6271b93dd48996e38d45633a5958d1b2d79d68405114b758828836",
>   "parentHash": "0x05003cf2c38f8bafd8b82a4617ff47dc2c2dd8fc5f8792e98139fc753f3d782e",
>   "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
>   "miner": "0xca40796afb5472abaed28907d5ed6fc74c04954a",
>   "stateRoot": "0x06eff4a5dc5808ca81ad5702fb4ec1510424cdfc8690167a4e7617511af9e962",
>   "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   "number": "0x1228",
>   "gasUsed": "0x0",
>   "gasLimit": "0x1312d00",
>   "extraData": "0x",
>   "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>   "timestamp": "0x662384f2",
>   "difficulty": "0x0",
>   "totalDifficulty": "0x0",
>   "sealFields": [],
>   "uncles": [],
>   "transactions": [],
>   "size": null,
>   "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
>   "nonce": "0x0000000000000000",
>   "baseFeePerGas": "0x0",
>   "withdrawalsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   "withdrawals": []
> }
> ```

excusme, what's is this `cast bl` command? I'd like to replicate what you did but so that we can check it from here as well. Thx!

**Comment by ChiTimesChi** [comment] 2024-04-26 13:32
@RafaDSan `cast` is part of the foundry toolkit, which is very helpful for developing/testing Solidity contracts, as well as interacting with RPC nodes in general:

https://github.com/foundry-rs/foundry

**Comment by RafaDSan** [comment] 2024-04-26 14:33
> @RafaDSan `cast` is part of the foundry toolkit, which is very helpful for developing/testing Solidity contracts, as well as interacting with RPC nodes in general:
> 
> https://github.com/foundry-rs/foundry

thx for the fast answer!

**Comment by jaylmiller** [comment] 2024-04-26 14:49
@0xneves Hi thanks for the notes on how to reproduce. I just followed and ran your indexer locally and i'm not getting the bug you encountered last week. I

took a look at the raw RPC data for blocks and it seems like it is correctly reporting `size` now as non-null.

Going to close this for now. We will have a more general fix for this issue (non-critical fields sometimes being null in RPC responses) in the near future.

**Comment by jaylmiller** [comment] 2024-05-06 19:03
@0xneves is it possible your chain's RPC may be down or not returning logs data (this would cause no events to be triggered)? if u send the address of the contract you are indexing, we can verify what's happening.

**Comment by RafaDSan** [comment] 2024-05-06 20:28
> @0xneves is it possible your chain's RPC may be down or not returning logs data (this would cause no events to be triggered)? if u send the address of the contract you are indexing, we can verify what's happening.

Hello, @jaylmiller ! The contract we have deployed on the network is: `0x80f14F36Eb515C8F254108f8c344D9ef44e3c33e`

The network could be quite unstable due to it's alpha phase and at the time I write this message, they are not available.
But we've tested when they were certainly online, with the RPC working
When they get online again, I'll send a message here, is that okay?

**Comment by RafaDSan** [comment] 2024-05-07 17:22
> > @0xneves is it possible your chain's RPC may be down or not returning logs data (this would cause no events to be triggered)? if u send the address of the contract you are indexing, we can verify what's happening.
> 
> Hello, @jaylmiller ! The contract we have deployed on the network is: `0x80f14F36Eb515C8F254108f8c344D9ef44e3c33e`
> 
> The network could be quite unstable due to it's alpha phase and at the time I write this message, they are not available. But we've tested when they were certainly online, with the RPC working When they get online again, I'll send a message here, is that okay?

the network is online now @jaylmiller @0xOlias

**Comment by jaylmiller** [comment] 2024-05-10 15:45
There are no logs associated with your address, so you aren't seeing any events. You can use cast to check for logs on your contract:
```sh
cast l --address 0x80f14F36Eb515C8F254108f8c344D9ef44e3c33e -r https://sepolia-rpc.kakarot.org
```

**Comment by RafaDSan** [comment] 2024-05-10 15:49
The network was reset and our contract was erased, and it seems it's not working again.  We'll have to wait a bit more to test it again

**Comment by RafaDSan** [comment] 2024-05-13 03:53
New address:  0xB317127b50b22e62637E3c333A585a8ccfd0721D
https://sepolia-explorer.kakarot.org/contracts/0xb317127b50b22e62637e3c333a585a8ccfd0721d

**Comment by RafaDSan** [comment] 2024-05-15 20:04
Hey team, I've opened this other issue #886 because the error `insertLogFilterInterval" in this issue was already solved by the blockchain team, so I think this issue could be closed. We are still having problems to fetch the events, but it's related to other problems now. I appreciate your help with this issues!

**Closed** 2024-05-15 20:05 UTC
